#!/usr/bin/python2.4
#
tricks = [
'Worm',
'Maggot',
'Snake',
'Cockroach',
'Mystery Meatloaf',
'Spider',
'Boogers',
'Scorpion',
'Leeches',
]

treats = [
'100 Grand Bar',
'3 Musketeers',
'5th Avenue',
'Abba-Zaba',
'Aero',
'Almond Joy',
'Baby Ruth',
'Banjo',
'Bar None',
'Bertie Beetle',
'Big Hunk',
'Big Turk',
'Bit-O-Honey',
'Blue Riband',
'Boost',
'Bounty',
'Brunch Bar',
'Butter Brickle',
'Butterfinger',
'Cadbury Creme Egg',
'Cadbury Flake',
'Cadbury Fudge',
'Cadbury Mr. Big',
'Cadbury Picnic',
'Cadbury Snack',
'Cadbury Snowflake',
'Cadbury Spira',
'Cadburys Tempo',
'Cajeta Elegancita',
'Caramac',
'Caramello Koala',
'Celebrations',
'Charleston Chew',
'Cherry Blossom',
'Cherry Mash',
'Cherry Ripe',
'Chick-O-Stick',
'Chocolate Crunchies',
'Chokito',
'Chomp',
'Choo Choo Bar',
'Nestle Chunky',
'Clark Bar',
'Coffee Crisp',
'Crachi',
'Crispy Crunch',
'Crunchie',
'Cup-o-Gold',
'Curly Wurly',
'Daim bar',
'Double Decker',
'Drifter',
'Dubble',
'Eat-More',
'Flyte',
'Freddo Frog',
'Fry\'s Chocolate Cream',
'Fry\'s Turkish Delight',
'Goetze\'s Candy Company',
'GooGoo Cluster',
'Heath bar',
'Hematogen',
'Heroes',
'Hershey bar',
'Hershey\'s Miniatures',
'Hershey\'s S\'mores',
'Hershey\'s Special Dark',
'Horalky',
'Idaho Spud',
'Kendal Mint Cake',
'Kismet',
'Kit Kat',
'Krackel',
'Krembanan',
'Kvikk Lunsj',
'Lion Bar',
'Lotte Ghana',
'M-Azing',
'Marathon',
'Mars Bar',
'Mary Jane',
'Maverick',
'Mekupelet',
'Milk Tray',
'Milky Way bar',
'Milkybar',
'Mounds',
'Mr. Goodbar',
'Nestle Crunch',
'Nut Goodie',
'NutRageous',
'Oh Henry!',
'PB Max',
'PayDay',
'Peanut Chews',
'Peppermint Crisp',
'Polly Waffle',
'Reese\'s Peanut Butter Cups',
'ReeseSticks',
'Ritter Sport',
'Rocky Road Candy',
'Salted Nut Roll',
'Scorched Peanut Bar',
'Skor',
'Sky Bar',
'Snack Barz',
'Snickers',
'Snickers Marathon',
'Star Bar',
'Sugar Mama',
'Summit Candy Bar',
'Time Out',
'Toblerone',
'Toffee Crisp',
'Topic',
'Tupla',
'Twix',
'U-No Bar',
'Violet Crumble',
'Walnut Whip',
'Wazoo',
'Whatchamacallit',
'Wispa',
'Wonka Bar',
'Wonka Xploder',
'Yankie bar',
'Yorkie',
'ZERO bar',
'Zagnut'
]
